font-family = Lilex
font-style-bold = false
theme = dark:Atom One Dark,light:Atom One Light

window-padding-balance = true
window-padding-x = 5
window-padding-y = 5

working-directory = "code"

keybind = ctrl+k=new_tab
keybind = ctrl+l=next_tab
keybind = ctrl+h=previous_tab
