"$schema" = "https://starship.rs/config-schema.json"
format = "$username$hostname$directory$git_branch$python$line_break$character"

add_newline = false

[username]
show_always = true
format = "[$user@]($style)"
style_user = "#FB4934"

[hostname]
ssh_only = false
format = "[$hostname ]($style)"
style = "#FB4934"

[directory]
truncation_length = 3
truncate_to_repo = false
format = "[$path ]($style)"
style = "white"

[git_branch]
format = "[git\\(]($style)[$branch](#B8BB26)[\\) ]($style)"
style = "white"

[python]
format = "[venv\\(]($style)[$virtualenv](#B8BB26)[\\) ]($style)"
style = "white"
