font-family = Lilex
theme = Gruvbox Dark

font-style-bold = false
fullscreen = true
window-vsync = true
window-padding-balance = true
window-show-tab-bar = never
adjust-cursor-thickness = 3

working-directory = "code"

keybind = F11=toggle_fullscreen
keybind = alt+l=next_tab
keybind = alt+h=previous_tab
keybind = alt+k=new_tab
keybind = alt+q=close_tab
keybind = alt+t=toggle_tab_overview
